[project]
name = "comfyui-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.4",
    "openai>=1.57.0",
    "requests>=2.32.3",
    "rich>=13.9.4",
]
